---
name: apply
on:
  push:
    branches: [main]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TFACTION_IS_APPLY: 'true'
permissions:
  id-token: write
  contents: read
  issues: read # this is required to `gh pr list`'s `-l` option
  pull-requests: write
jobs:

  apply:
    uses: codimite/tfaction-workflows/.github/workflows/apply.yaml@main
    secrets:
      gh_app_id: ${{secrets.APP_ID}}
      gh_app_private_key: ${{secrets.APP_PRIVATE_KEY}}
      secrets: ${{toJSON(secrets)}}
      gh_token: ${{github.token}}
      tfe_token: ${{secrets.TF_API_TOKEN}}
